# Generated by Django 6.0.5 on 2026-10-04 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('FIXED_SERVICE', 'Fixed service'), ('CUSTOM_JOB', 'Custom job'), ('LOCAL_APPOINTMENT', 'Local appointment'), ('REMOTE_PROJECT', 'Remote project'), ('MILESTONE_PROJECT', 'Milestone project')], default='CUSTOM_JOB', max_length=40)),
                ('service_mode', models.CharField(choices=[('LOCAL', 'Local'), ('REMOTE', 'Remote')], default='LOCAL', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('requirements', models.TextField(blank=True)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('appointment_start', models.DateTimeField(blank=True, null=True)),
                ('appointment_end', models.DateTimeField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=500)),
                ('location_city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('revision_limit', models.PositiveSmallIntegerField(default=1)),
                ('revisions_used', models.PositiveSmallIntegerField(default=0)),
                ('open_to_all', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PROVIDER_RESPONSE', 'Pending provider response'), ('COUNTER_OFFERED', 'Counter offered'), ('AGREEMENT_REACHED', 'Agreement reached'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_FAILED', 'Payment failed'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('DELIVERABLE_SUBMITTED', 'Deliverable submitted'), ('CLIENT_REVIEWING', 'Client reviewing'), ('REVISION_REQUESTED', 'Revision requested'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], default='PENDING_PROVIDER_RESPONSE', max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_bookings', to='catalog.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bookings', to='accounts.clientprofile')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_bookings', to='accounts.freelancerprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_bookings', to='catalog.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bookings.projectbooking')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='deliverables/')),
                ('link_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_deliverables', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='bookings.projectbooking')),
            ],
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_counter_offers', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='bookings.projectbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='booking_attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_attachments', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.projectbooking')),
            ],
        ),
    ]
